import * as github from "@actions/github";

const MARKER = "<!-- ai-commit-msg -->";

export async function postComment(
  token: string,
  context: typeof github.context,
  message: string,
): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = context.repo;
  const prNumber = context.payload.pull_request?.number;

  if (!prNumber) return;

  const body = `${MARKER}\n### AI Commit Summary\n\n\`\`\`\n${message}\n\`\`\`\n\n<sub>Generated by [ai-commit-msg](https://github.com/ofershap/ai-commit-msg)</sub>`;

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const existing = comments.find((c) => c.body?.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }
}
